### ISSUE TITLE
Does not work on Windows environments

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-latex-maven-plugin#1]
I was experimenting with this tool when working on a ticket for the [Thindeck.com project](https://github.com/yegor256/thindeck). However, I can't build any images, because it gives me the following error:

```
[ERROR] Failed to execute goal com.texry:texry-maven-plugin:0.2.1:compile (default) on project thindeck: Failed to compile 'classes-1.tex': Cannot run program "/usr/bin/which": CreateProcess error=2, The system cannot find the file specified -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.texry:texry-maven-plugin:0.2.1:compile (default) on project thindeck: Failed to compile 'classes-1.tex'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to compile 'classes-1.tex'
        at com.texry.maven.CompileMojo.compile(CompileMojo.java:144)
        at com.texry.maven.CompileMojo.execute(CompileMojo.java:114)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.io.IOException: Cannot run program "/usr/bin/which": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at com.texry.maven.Compiler.bin(Compiler.java:209)
        at com.texry.maven.Compiler.process(Compiler.java:117)
        at com.texry.maven.Compiler.compile(Compiler.java:81)
        at com.texry.maven.CompileMojo.compile(CompileMojo.java:134)
        ... 22 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:189)
        at java.lang.ProcessImpl.start(ProcessImpl.java:133)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1021)
        ... 26 more
```

This is because I am running on Windows 7, which does not have the `which` command. There should be a way the tool to be run on Windows environments. We should find a way of running it without needing to rely on hard-coded invocations of Unix commands.

**Comment by darkled** [comment]
@yegor256 what about releasing a new version to maven central? is it not there yet?

**Comment by yegor256** [comment]
@rultor release, tag is `1.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.1`

**Comment by yegor256** [comment]
@darkled 1.1 is in Maven Central

**Comment by darkled** [comment]
@yegor256 thanks.

@carlosmiranda could you, please, check it now?

**Comment by carlosmiranda** [comment]
@darkled Thanks, the error above has been fixed. However, I am now getting a different error.

I'm closing this now, let's continue with #9.

**Comment by dmarkov** [comment]
@darkled Thanks a lot, I just topped your account for **30 mins**, transaction ID `50043348`

added +30 to your rating, now it is equal to [+0](http://www.netbout.com/b/35091?open=rating)
